# Generated by Django 5.0.7 on 2024-09-25 01:28

import drones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_alter_drone_name_alter_dronecategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, unique=True)),
                ('old', models.IntegerField(validators=[drones.models.validate_even])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
